export const GOOGLE_EMAIL = "peche-test@peche-test.iam.gserviceaccount.com"

export const GOOGLE_PRIVATE_KEY =
  "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQD0BLb0n2bnUNyQ\npswH8dX6kTcARyx29Qlf1KEpy2CEzw9Sv2JsIFa+VwmqZxZNXdLbG1cCt7IXwxsT\nTEZktIvir2P5womLc7nbKkGXvITOp51jJ0tjQaMgXTiryTOvURTcIvJbxgz4peI8\nnTQGsso3WOP96YlWHx8EtComE4+AuwvuUsGle7p54bGDAY9Bzr8lw6YXMIEhFCvK\nS5CmqkJnGwPZqeKzIsORPAunBY2vcQiJx0D55Flm2GvqqrRHZ1uflN6ncD8f/swp\nZ1A+gYe1CYhGLfjCqXE0Jf/lpGwHEbsDb1L/SaGujGdfOepoB+BMKYgpiO2EuYFI\no3i+RKILAgMBAAECggEAAzcSsAtvoCmdFlzUQGCL2LbUGjFV4SVeX8Bd9T6EQYu2\n4Hi8E7+jVPOxoWilTxSm5BMqpNMFyjFcaHcvUEFevHhiIVbSWB+Iud4HKjgmKdDk\njntkj2S8gP8pcX3/q9YuJ65gMhxcbGRHJFRP7KyrZGpL6rsKf7N+RaIYEhNc5y3J\nJsZZgZS1wnGxX0cAo2a5d1ehVXsESIgQEkp1oe0tLGZDUjn57OOGGuVHn0U97nOg\n5f/9PKDp/FdylJoHs7vvd/ZswTNP+ifhiex4pT4sZrK7eRduNl1bAOufK9sfjblw\ngEManMIEStikpnVjpOgiougthFR6rhli67MechZXJQKBgQD8aXSgsao0laVmtrTt\noZzeAnOWs3rXd/Fo+PH7FG+7EcZCMO19/O4ISiXNt3BtP8RWznLbI9RP/wRv8vU3\nogiKmgKy5ogZ6qcadSXp9tJFNXEa4KzHT3o60hMe8lW5n6Ht80dJHByUjIQ/hvOP\nvnoO7iY5/5/xbkc2HPBY1V/ODwKBgQD3fLbpYqIirWcvrhjGRKCAUkY5dIEcFT5z\nQnF4/vDTprr49BlKg6xbsM/TVz0EEO9xqBezLeuvgAKNhMt705Qe3/N/Bhy3Omyv\niduK1I9+uC5jqlBViBC3HdlWNcbxAQJWaoxIL8ZPbyHzCxt77Vy9V9eZUOWShZop\npPF88IRoRQKBgQDxC9xe4YwDr61HC9B45s+hjIHKNxhm0JpwftzHxFp3MaA98e+7\nU2IV9IlpjXcGPdFIfNtevzawNn+MUV8wg8LYaf+NzW3IIjj2oU1Vw2pGwaSD4G/f\n3tyBc8Di2tZW8EV5scwv23LHwfFBoaTTbzmtLGzBEocxzvieisBUdWCKrQKBgQDd\nnaI1b4t8vgaOnbm1obKP9hzISllrCmL312HBVZnWDZGUaRFUtoBbQwN3XsFWqMuh\n3UILw20vpNOkYmvMoHQdCbID5zdDpF+6+RnNQfaVJNz1hoeVb9h4AZSjLFjPa3Xq\naFLiOVW9v+iIuUONP8oyCz0XH2fUQyr/a6KLnN0UeQKBgQDOQ4Se1rzX2neL+RFk\nC7U/ulO2tm3+zugx0vw5hsWT6bda6HvXcpXbGR0pf9bn5zCCTpoSbUPSxR9hJ4/7\ncuwHgNyonoScoLKIAwxcayN/GU7BIVyYhBXvduEL3cHxKSVmv95mjrN1xM2KOrg5\n9tCLhyIWHzwEh5Hiwf3HOxWgyQ==\n-----END PRIVATE KEY-----\n"

export const PRODUCT_COLUMN_NUMBER = {
  VISIBLE: 0,
  VISIBLE_JA: 1,
  VISIBLE_EN: 2,
  VISIBLE_ZH: 3,
  VISIBLE_ZHTW: 4,
  VISIBLE_TH: 5,
  CATEGORY: 6,
  DETAIL_PAGE: 7,
  NAME: 8,
  DESCRIPTION: 9,
  PRICE: 10,
  DISCOUNT_PRICE: 11,
  NAME_JA: 12,
  DESCRIPTION_JA: 13,
  NAME_EN: 14,
  DESCRIPTION_EN: 15,
  NAME_ZH: 16,
  DESCRIPTION_ZH: 17,
  NAME_ZHTW: 18,
  DESCRIPTION_ZHTW: 19,
  NAME_TH: 20,
  DESCRIPTION_TH: 21,
}

export const EVENT_COLUMN_NUMBER = {
  VISIBLE: 0,
  VISIBLE_JA: 1,
  VISIBLE_EN: 2,
  VISIBLE_ZH: 3,
  VISIBLE_ZHTW: 4,
  VISIBLE_TH: 5,
  CATEGORY: 6,
  DETAIL_PAGE: 7,
  NAME: 8,
  DESCRIPTION: 9,
  PRICE: 10,
  DISCOUNT_PRICE: 11,
  NAME_JA: 12,
  DESCRIPTION_JA: 13,
  NAME_EN: 14,
  DESCRIPTION_EN: 15,
  NAME_ZH: 16,
  DESCRIPTION_ZH: 17,
  NAME_ZHTW: 18,
  DESCRIPTION_ZHTW: 19,
  NAME_TH: 20,
  DESCRIPTION_TH: 21,
  LABEL_NEW: 22,
  LABEL_POP: 23,
  LABEL_BEST: 24,
  LABEL_KAKAO: 25,
}

export const SHEET_TRUE_KEY = "노출"

// V2: 3-탭 시트 구조
export const CATEGORY_SHEET_NAME = "대분류"
export const DETAIL_PAGE_SHEET_NAME = "상세페이지"
export const PRODUCT_SHEET_NAME = "상품목록"

export const CATEGORY_COLUMN_NUMBER = {
  ORDER: 0,
  NAME: 1,
  NAME_JA: 2,
  NAME_EN: 3,
  NAME_ZH: 4,
  NAME_ZHTW: 5,
  NAME_TH: 6,
}

export const DETAIL_PAGE_COLUMN_NUMBER = {
  CATEGORY_NAME: 0,
  ORDER: 1,
  NAME: 2,
  NAME_JA: 3,
  NAME_EN: 4,
  NAME_ZH: 5,
  NAME_ZHTW: 6,
  NAME_TH: 7,
  DESCRIPTION: 8,
  DESCRIPTION_JA: 9,
  DESCRIPTION_EN: 10,
  DESCRIPTION_ZH: 11,
  DESCRIPTION_ZHTW: 12,
  DESCRIPTION_TH: 13,
}
