### login
POST {{xen_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### create close-days
POST {{xen_host}}/close-days
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "memo": "test close day",
  "date": "2023-12-30"
}

### get close-days
GET {{xen_host}}/close-days
Authorization: Bearer {{user_auth_token}}
