### get admin token
POST {{api_host}}/admin-auth/admin-jwt
Content-Type: application/json

> {%
  client.global.set("admin_auth_token", response.body);
  client.global.set("user_auth_token", response.body);
%}

### get admin user
GET {{api_host}}/admin/users
Content-Type: application/json
Authorization: Bearer {{admin_auth_token}}

> {%
  client.global.set("user_id", response.body.items[0].id);
%}


### login
POST {{api_host}}/admin-auth/{{user_id}}/jwt
Content-Type: application/json

> {%
  client.global.set("user_auth_token", response.body);
%}

### get product
GET {{api_host}}/products
Authorization: Bearer {{user_auth_token}}

> {%
  client.global.set("product_id_1", response.body.items[0].id);
  client.global.set("product_id_2", response.body.items[1].id);
%}

### create reservations
POST {{api_host}}/reservations
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "datetime": "2024-03-18 10:00:00",
  "status": "WAITING",
  "productIds": ["{{product_id_1}}", "{{product_id_2}}"],
  "userMemo": "잘해주세요",
  "pathVisit": "1",
  "detailVisit": "1"
}

### update reservations
PUT {{api_host}}/reservations/92289abb-9d17-49ca-b25b-268067e904d8
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "status": "DONE"
}

### get reservations
GET {{api_host}}/reservations?createdAtBetween=2023-12-01T00:00:00.000Z&createdAtBetween=2023-12-28T23:59:59.999Z
Authorization: Bearer {{user_auth_token}}

### get available-by-month
GET {{api_host}}/reservations/available-by-month?year=2024&month=3&productIds={{product_id_1}}&
    productIds={{product_id_2}}
Authorization: Bearer {{user_auth_token}}

### get available-by-day
GET {{api_host}}/reservations/available-by-day?year=2024&month=3&day=29&productIds={{product_id_1}}&
    productIds={{product_id_2}}
Authorization: Bearer {{user_auth_token}}

### get count-by-month
GET {{api_host}}/reservations/count-by-month?year=2024&month=1
Authorization: Bearer {{user_auth_token}}

### get available-by-month
GET {{api_host}}/reservations/available-by-month?year=2024&month=3&eventIds=82356cd1-15c8-4580-9069-e65518173107&
    eventIds=dd9c6f84-6222-4b90-89c5-e5b790e37dfc
Authorization: Bearer {{user_auth_token}}

### get available-by-day
GET {{api_host}}/reservations/available-by-day?year=2024&month=3&day=19&eventIds=82356cd1-15c8-4580-9069-e65518173107&
    eventIds=dd9c6f84-6222-4b90-89c5-e5b790e37dfc
Authorization: Bearer {{user_auth_token}}
