### login
POST {{api_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### create specific-date
POST {{api_host}}/specific-date
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "date": "2023-12-31",
  "slots": [
    {
      "building": "MAIN",
      "hour": 10,
      "minutes": 0,
      "maxSlot": 5
    },
    {
      "building": "MAIN",
      "hour": 11,
      "minutes": 0,
      "maxSlot": 5
    }
  ]
}

### get specific-date
GET {{api_host}}/specific-date
Authorization: Bearer {{user_auth_token}}
