### login
POST {{xen_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### create equipment
POST {{xen_host}}/equipments
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "status": "ACTIVE",
  "name": "test-equipment"

}

### get equipment
GET {{xen_host}}/equipments
Authorization: Bearer {{user_auth_token}}
