### login
POST {{api_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### create main-images
POST {{api_host}}/main-images
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "status": "ACTIVE",
  "description": "test-main-images"

}

### get main-images
GET {{api_host}}/main-images
Authorization: Bearer {{user_auth_token}}
