### login
POST {{xen_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### create main-popup
POST {{xen_host}}/main-popup
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "status": "ACTIVE",
  "description": "test-main-popup"

}

### get main-popup
GET {{xen_host}}/main-popup
Authorization: Bearer {{user_auth_token}}
