### login
POST {{xen_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### create search-keywords
POST {{xen_host}}/search-keywords
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "languageLocale": "KO",
  "keyword": "test-keywords"
}

### get search-keywords
GET {{xen_host}}/search-keywords
Authorization: Bearer {{user_auth_token}}
