### login
POST {{api_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### refresh crm-categories
POST {{api_host}}/crm-categories
Authorization: Bearer {{user_auth_token}}

### get crm-categories
GET {{api_host}}/crm-categories
Authorization: Bearer {{user_auth_token}}

> {%
  client.global.set("crm_category_code", response.body[0].code);
%}

### update crm-categories
PUT {{api_host}}/crm-categories/{{crm_category_code}}
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "maxSlot": 5
}
