### get admin token
POST {{api_host}}/admin-auth/admin-jwt
Content-Type: application/json

> {%
  client.global.set("admin_auth_token", response.body);
  client.global.set("user_auth_token", response.body);
%}


### create user
POST {{api_host}}/admin/users
Content-Type: application/json
Authorization: Bearer {{admin_auth_token}}

{
  "email": "test@test.com",
  "password": "peche121"
}

> {%
  client.global.set("user_id", response.body.id);
%}


### set admin user
PUT {{api_host}}/admin/users/{{user_id}}/admin
Content-Type: application/json
Authorization: Bearer {{admin_auth_token}}


### remove admin user
DELETE {{api_host}}/admin/users/{{user_id}}/admin
Content-Type: application/json
Authorization: Bearer {{admin_auth_token}}


### get admin user
GET {{api_host}}/admin/users?role=ADMIN
Content-Type: application/json
Authorization: Bearer {{admin_auth_token}}
