### login
POST {{api_host}}/auth/login
Content-Type: application/json

{
  "phoneNumber": "+821012345678",
  "password": "12345678"
}

> {%
  client.global.set("user_auth_token", response.body);
%}

### get product-categories
GET {{api_host}}/product-categories
Authorization: Bearer {{user_auth_token}}

> {%
  client.global.set("product_category_id", response.body[0].id);
%}

### get product-categories
GET {{api_host}}/product-detail-pages
Authorization: Bearer {{user_auth_token}}

> {%
  client.global.set("product_detail_page_id", response.body[0].id);
%}

### get integrated-crm-categories
GET {{api_host}}/integrated-crm-categories
Authorization: Bearer {{user_auth_token}}

> {%
  client.global.set("integrated_crm_category_id", response.body[0].id);
%}

### create product
POST {{api_host}}/products
Authorization: Bearer {{user_auth_token}}
Content-Type: application/json

{
  "categoryId": "{{product_category_id}}",
  "detailPageId": "{{product_detail_page_id}}",
  "integratedCrmCategoryId": "{{integrated_crm_category_id}}",
  "name": "test product",
  "description": "test",
  "price": 1000,
  "order": 1,
  "visible": true,
  "visibleEN": true,
  "visibleZH": true,
  "visibleJA": true,
  "visibleTH": true
}

### get product
GET {{api_host}}/products
Authorization: Bearer {{user_auth_token}}
